services:
  mysql-db:
    image: mysql:8.0
    container_name: nexusmarket-mysql
    restart: always
    environment:
      MYSQL_DATABASE: nexusmarket_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo-db:
    image: mongo:6.0
    container_name: nexusmarket-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
